services:
  - type: web
    name: hotel-ai-assistant
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python data/seed.py
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
